name: build_deploy_aks
on:
  push:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      # Login to Azure using service principal stored in AZURE_CREDENTIALS
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: ACR Login
        run: az acr login --name ${{ secrets.registry }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build ./azure-vote \
            -t ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}
          docker push ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}

      # Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }} 
          cluster-name: ${{ secrets.cluster_name }}

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      # Deploy manifests to AKS
      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            azure-vote-all-in-one-redis.yaml
          images: |
            ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}
          pull-images: false

      # Verify pods are running
      - name: Get pods
        run: kubectl get pods -o wide | grep vote
